- name: Create nginx directory
  ansible.builtin.file:
    dest: "/home/{{ ansible_ssh_user }}/test-project/nginx"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0755"

- name: Generate nginx config
  ansible.builtin.template:
    src: default.conf.j2
    dest: "/home/{{ ansible_ssh_user }}/test-project/nginx/default.conf"
    mode: "0775"
