services:
  php:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./php:/var/www/html
    restart: always
    networks:
      - internal
    depends_on: 
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    restart: always
    depends_on: 
      - php
    networks:
      - internal

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=passwd123
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=passwd123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  
networks:
  internal:
     driver: bridge

volumes:
  db_data: